### ISSUE TITLE
Integración de servicio de mongo para movimiento reducción en MID

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/movimientos_mid#2]
- [x] crear los endpoints necesarios para registrar movimiento de reducción en MID
---
Integración de servicio de mongo para movimiento reducción en MID 5 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Se espera socializacion del 09/07/2019 para definir la metodología de esta tarea.

**Comment by miguelramirez93** [comment]
Esta tarea se completo en (https://github.com/udistrital/plan_cuentas_mid/issues/20) con la generalización del registro de movimientos presupuestales.

**Comment by Soulfilip-UD** [comment]
Buen Trabajo !
Proceeding to close Issue 👾
