### ISSUE TITLE
Integracion de servicio de mongo para movimiento de traslado 

### ISSUE THREAD

**Issue by macaguegi** [udistrital/movimientos_mid#3]
Se debe articular el servicio de Mongo para poder llevar a cabo el movimiento de traslado de fuente de financiamiento.

- [x] crear los endpoints necesarios para registrar movimiento de traslado en MID

**Comment by macaguegi** [comment]
Se espera socializacion del 09/07/2019 para definir la metodología de esta tarea

**Comment by macaguegi** [comment]
Se asocia esta tarea al merge #23 realizado por @juancsr y tambien se le asigna esta tarea para pruebas y documentación .

**Comment by juancsr** [comment]
* **Tipo de petición**: POST
* **Parámetros**:
```json
[
	{ 
		"Valor": 30000000.0,
		"FechaRegistro": "2019-05-01T05:00:00.000Z",
		"Descripcion": "Traslado de la fuente de financimiento 3 a la fuente de financiamiento 5",
		"MovimientoProcesoExternoId": {
			"TipoMovimientoId": {
				"Id": 3
			},
			"ProcesoExterno": 9
		}
	}
]
```
* **Endpoint**: movimiento/
* **URL**: http://localhost:8084/v1/movimiento/

**Comment by Soulfilip-UD** [comment]
Buen trabajo en equipo!
Proceeding to close Issue 👾
